name: Build and deploy ASP app to Azure Web App - conclase-tech-dictionary

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup MSBuild path
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5

      - name: Restore NuGet packages
        run: nuget restore ./TechDictionaryApi.csproj  # Replace with your actual .csproj path if different
        working-directory: D:/a/TechDictionaryApi-backend-fork/TechDictionaryApi-backend-fork

      # Use MSBuild to publish the project to a folder
      - name: Publish to folder
        run: msbuild ./TechDictionaryApi.csproj /nologo /verbosity:m /t:Publish /p:Configuration=Release /p:PublishDir="D:/a/TechDictionaryApi-backend-fork/TechDictionaryApi-backend-fork/published/"
        working-directory: D:/a/TechDictionaryApi-backend-fork/TechDictionaryApi-backend-fork

      # Upload the published output as an artifact
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: ASP-app
          path: 'D:/a/TechDictionaryApi-backend-fork/TechDictionaryApi-backend-fork/published/**'

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: ASP-app
      
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'conclase-tech-dictionary'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_79AD93A816A34040BCA5E1CEFE944DEB }}
